### ISSUE TITLE
parse and parse! and parse_address and parse_address!

### ISSUE THREAD

**Issue by micahwedemeyer** [Cobenian/inet_cidr#1]
I've got a form input where someone can input either an IPv4, possibly in CIDR notation. I'd love to just hand the user-entered string to `parse` or `parse_address` and have it return either `:ok` or `:error` instead of throwing an exception.

Would you consider having both the tuple and exception versions of these functions? If I submitted a PR with that, would you accept it?

**Comment by brweber2** [comment]
We would accept it assuming it follows standard conventions. Thanks!

**Comment by brweber2** [comment]
Please update to version `1.0.7`. Functions updated to follow Elixir idioms.

- `parse/1` has been ***deprecated***.
- `parse_cidr/` has been added
- `parse_cidr!/1` has been added
- `parse_address/1` has been added
