### ISSUE TITLE
Version bump and push to hex.pm

### ISSUE THREAD

**Issue by mrinalwadhwa** [Cobenian/inet_cidr#6]
The version of on Github master is, after the recent changes, not the same as the version on hex. Even though both are `1.0.2`
https://github.com/Cobenian/inet_cidr/blob/master/mix.exs#L6

@brweber2 it would help me (and any other users) a lot if you could bump the version and push to hex. Thanks.

**Comment by brweber2** [comment]
Correct, the version of master hasn’t been deployed as 1.0.3 to hex yet. I will get to that at some point in the near future. Possibly as soon as today but no promises.

**Comment by brweber2** [comment]
Deployed 1.0.3. Please let me know if you encounter any issues.

**Comment by mrinalwadhwa** [comment]
Works well. Thank you @brweber2
