### ISSUE TITLE
Proposal: Expose calc_end_address

### ISSUE THREAD

**Issue by rockwood** [Cobenian/inet_cidr#9]
I have pre-parsed v4 and v6 ip addresses in the form of `%Postgrex.Inet{address: {1, 1, 1, 1}, subnet: 24}`.  Would it be possible to expose the `calc_end_address/2` function so I could get the end address without needing to convert them to strings and calling `parse`?

**Comment by brweber2** [comment]
Please upgrade to version `1.0.7`.  

- `calc_end_address/2` is now public.
